name: assarickym
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  injectable: ^2.1.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  dio: ^5.0.1
  flutter_riverpod: ^2.2.0
  page_transition: ^2.0.9
  lottie: ^2.3.2
  flutter_svg: ^2.0.0+1
  go_router: ^6.2.0
  http: ^0.13.6
  shared_preferences: ^2.1.1


dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.4
  retrofit_generator: ^5.0.0


flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/poppins/Poppins-ExtraBold.ttf
        - asset: assets/poppins/Poppins-Bold.ttf
        - asset: assets/poppins/Poppins-SemiBold.ttf
        - asset: assets/poppins/Poppins-Medium.ttf
        - asset: assets/poppins/Poppins-Regular.ttf
        - asset: assets/poppins/Poppins-Light.ttf
  assets:
    - assets/
    - assets/svg/

